services:
  app:
    platform: "linux/amd64"
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    image: pz-poker-app
    ports:
      - 3000:3000
    env_file:
      - .env

  db:
    image: postgres:latest
    container_name: pz-poker-postgres-local
    restart: unless-stopped
    hostname: localhost
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - pz-poker-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
  
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    environment:
      TUNNEL_TOKEN: ${TUNNEL_TOKEN}

volumes:
  pz-poker-postgres-data:
    driver: local